export const feasibilityActionTypes = {
    FEASIBILITY_CHECK_STARTED: 'FEASIBILITY_CHECK_STARTED',
    FEASIBILITY_CHECK_SUCCESS: 'FEASIBILITY_CHECK_SUCCESS',
    FEASIBILITY_CHECK_FAILED: 'FEASIBILITY_CHECK_FAILED',
};

export const offeringsActionTypes = {
    read_offering_detail: 'Read_Offering_Detail',
    read_offering_detail_success: 'READ_OFFERING_DETAIL_SUCCESS',
    read_offering_detail_error: 'READ_OFFERING_DETAIL_ERROR'
};

export const FetchProjectNameActionTypes = {
    GET_PROJECT_NAME_STARTED: 'GET_PROJECT_NAME_STARTED',
    GET_PROJECT_NAME_SUCCESS: 'GET_PROJECT_NAME_SUCCESS',
    GET_PROJECT_NAME_FAILED: 'GET_PROJECT_NAME_FAILED'
};
export const FetchOrgsDataActionTypes = {
    GET_ORGS_DATA_STARTED: 'GET_ORGS_DATA_STARTED',
    GET_ORGS_DATA_SUCCESS: 'GET_ORGS_DATA_SUCCESS',
    GET_ORGS_DATA_FAILED: 'GET_ORGS_DATA_FAILED'
};
export const FetchLocsDataActionTypes = {
    GET_LOCS_DATA_STARTED: 'GET_LOCS_DATA_STARTED',
    GET_LOCS_DATA_SUCCESS: 'GET_LOCS_DATA_SUCCESS',
    GET_LOCS_DATA_FAILED: 'GET_LOCS_DATA_FAILED'
};
export const FetchFunctDataActionTypes = {
    GET_FUNCTS_DATA_STARTED: 'GET_FUNCTS_DATA_STARTED',
    GET_FUNCTS_DATA_SUCCESS: 'GET_FUNCTS_DATA_SUCCESS',
    GET_FUNCTS_DATA_FAILED: 'GET_FUNCTS_DATA_FAILED'
};
export const FetchRoleActionTypes = {
    GET_ROLES_STARTED: 'GET_ROLES_STARTED',
    GET_ROLES_SUCCESS: 'GET_ROLES_SUCCESS',
    GET_ROLES_FAILED: 'GET_ROLES_FAILED'
};
export const FetchResourceActionTypes = {
    GET_RESOURCES_STARTED: 'GET_RESOURCES_STARTED',
    GET_RESOURCES_SUCCESS: 'GET_RESOURCES_SUCCESS',
    GET_RESOURCES_FAILED: 'GET_RESOURCES_FAILED'
};
export const FetchMenuActionTypes = {
    GET_MENUS_STARTED: 'GET_MENUS_STARTED',
    GET_MENUS_SUCCESS: 'GET_MENUS_SUCCESS',
    GET_MENUS_FAILED: 'GET_MENUS_FAILED'
};
export const ProfileActionTypes = {
    functions: {
        FETCH_FUNCTIONS: 'FETCH_FUNCTIONS'
    },
    studyConfig: {
        ADD_STUDY_CONFIG_GROUPS: 'ADD_STUDY_CONFIG_GROUPS',
        ADD_STUDY_CONFIG: 'ADD_STUDY_CONFIG',
        DELETE_STUDY_CONFIG_GROUPS: 'DELETE_STUDY_CONFIG_GROUPS',
        UPDATE_STUDY_CONFIG: 'UPDATE_STUDY_CONFIG',
        DELETE_STUDY_CONFIG: 'DELETE_STUDY_CONFIG',
        FETCH_RA_CONFIG: 'FETCH_RA_CONFIG'
    },
    enrollmentTarget: {
        ADD_ENROLLMENT_TARGET: 'ADD_ENROLLMENT_TARGET',
        DELETE_ENROLLMENT_TARGET: 'DELETE_ENROLLMENT_TARGET',
        UPDATE_ENROLLMENT_TARGET: 'UPDATE_ENROLLMENT_TARGET',
        FETCH_ENROLLMENT_TARGET: 'FETCH_ENROLLMENT_TARGET'
    },
};

export const PublishActionTypes = {
    tenantPublish: {
        PUBLISH_TENANT: 'PUBLISH_TENANT',
        NEW_PROJECT: 'NEW_PROJECT'
    }
};


